### ISSUE TITLE
Изучить возможность финансирования проекта от Microsoft

### ISSUE THREAD

**Issue by NikolaySavenko** [NikolaySavenko/domus-sapiens#16]
Проект с открытым исходным кодом может быть профинансирован Microsoft. Необходимо изучить подробности и понять можем ли мы подойти под их условия и получить финансирование.

https://opensource.microsoft.com/azure-credits

**Comment by DashaZ1** [comment]
[Кредиты Azure для проектов с открытым исходным кодом.docx](https://github.com/NikolaySavenko/domus-sapiens/files/7620925/Azure.docx)
