### ISSUE TITLE
Сделать шаблон .env

### ISSUE THREAD

**Issue by NikolaySavenko** [NikolaySavenko/domus-sapiens#67]

**Comment by Andrey529** [comment]
Ссылка на страничку с шаблоном .env файла в wiki:
https://github.com/NikolaySavenko/domus-sapiens/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD-.env-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0-%D0%B4%D0%BB%D1%8F-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B8-%D0%B2%D1%81%D0%B5%D1%85-%D0%BA%D0%BE%D0%BD%D1%82%D0%B5%D0%B9%D0%BD%D0%B5%D1%80%D0%BE%D0%B2-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-docker-compose-%D1%84%D0%B0%D0%B9%D0%BB
