### ISSUE TITLE
Продумать компоновку и корпус устройства

### ISSUE THREAD

**Issue by NikolaySavenko** [NikolaySavenko/domus-sapiens#70]
Должна быть коробочка, которую можно вставлять вместо обычного выключателя. Должен быть доступ ко всем пинам

**Comment by zartavr** [comment]
Для презентации рабочего устройства (который мы потащим в аудиторию) удобнее будет использовать собранный на коленке макет. Примерно так это будет выглядеть 

![image](https://user-images.githubusercontent.com/63353823/140066045-ef63bbc1-1b68-46d1-89e9-d46ba4a8cbe0.png)

Нам не нужно будет блок питания собирать, можно использовать зарядку от телефона (точно никого током не ударит)). Кроме этого очень удобная демонстрация вкл/выкл козетки по кнопке.

Для презентации проекта могу сделать упрощенные 3-d модельки устройств. Это не совсем конечный продукт, т.к. будут другие размеры плат (реле и питание можно развести на одной плате, ESP32-WROOM компактнее dev-kita). Можно, конечно, и эту модель доработать и распечатать на 3-d принтере, но не уверен, что есть смысл так усложнять демонстрационный вариант рабочего устройства. Ниже прикрепил скрины 3-d модели выключателя, которую сегодня набросал. Есть ещё идея сделать вариант, утапливаемый в стену.

В общем, жду комментариев. Ну и могу Дане попробовать помогать с кодом для ESP, если у него ещё много задач запланировано

![aD2RmRzKtZU](https://user-images.githubusercontent.com/63353823/140063310-a0bc9565-b669-402d-b131-b4e36243cced.jpg)
![4IgYQPkKhiE](https://user-images.githubusercontent.com/63353823/140063331-33894129-065f-4fe5-b958-1ea9a72b5770.jpg)
![dTfxnY9hx3o](https://user-images.githubusercontent.com/63353823/140063339-b37ccef0-05c9-4414-b5a5-73465a3c821f.jpg)
![tpDd4iIYWOU](https://user-images.githubusercontent.com/63353823/140063343-41b4c689-9a2c-4074-a61e-e55003312d20.jpg)

**Comment by NikolaySavenko** [comment]
Нужен вариант утопленный в стену. В качестве ESP32 не будет использоваться Dev kit. Корпус скорее нужен на будущее, чем на реальный вариант этого семестра
